name: Build

on:
  workflow_dispatch:
  push:
    branches: [master, workflow]
  pull_request:
    branches: [master, workflow]

env:
  CARGO_TERM_COLOR: always
  ONDK_VERSION: "r29.5"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [debug, release]
        zygisk:
          - name: zygisk
            feature: "zynx/zygisk"
          - name: no-zygisk
            feature: ""
        bridge:
          - name: embedded-bridge
            feature: "zynx/embedded-bridge"
            split: false
          - name: split-bridge
            feature: ""
            split: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup just
        uses: extractions/setup-just@v4

      - name: Setup Protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Setup Rust (nightly for eBPF)
        run: rustup toolchain install nightly --component rust-src

      - name: Setup ONDK
        run: python3 scripts/setup-ondk.py --version $ONDK_VERSION

      - name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.21.1

      - name: Install bpf-linker
        run: cargo binstall bpf-linker --no-confirm

      - name: Build
        shell: bash
        run: |
          features=()
          for feature in '${{ matrix.zygisk.feature }}' '${{ matrix.bridge.feature }}'; do
            [[ -n "$feature" ]] && features+=("$feature")
          done
          feature_list="$(IFS=,; echo "${features[*]}")"
          just build ${{ matrix.profile }} "$feature_list" false

      - name: Upload embedded-bridge artifact
        if: ${{ !matrix.bridge.split }}
        uses: actions/upload-artifact@v7
        with:
          name: zynx-${{ matrix.profile }}-${{ matrix.zygisk.name }}-${{ matrix.bridge.name }}
          path: |
            target/aarch64-linux-android/${{ matrix.profile }}/zynx
            target/aarch64-linux-android/${{ matrix.profile }}/zynx.dwp
            target/aarch64-linux-android/${{ matrix.profile }}/libzynx_bridge.so.dwp

      - name: Upload split-bridge artifact
        if: ${{ matrix.bridge.split }}
        uses: actions/upload-artifact@v7
        with:
          name: zynx-${{ matrix.profile }}-${{ matrix.zygisk.name }}-${{ matrix.bridge.name }}
          path: |
            target/aarch64-linux-android/${{ matrix.profile }}/zynx
            target/aarch64-linux-android/${{ matrix.profile }}/zynx.dwp
            target/aarch64-linux-android/${{ matrix.profile }}/libzynx_bridge.so
            target/aarch64-linux-android/${{ matrix.profile }}/libzynx_bridge.so.dwp
